### PR TITLE
Update pools

### PR DESCRIPTION
**Pull request by happysmash27**
Specifically, added Minilaro. Another update will likely be needed in the future, since I plan on changing the domain name upon liquidity.

### CODE REVIEW

**Comment by scottdonaldau** [comment]
Hey @happysmash27 

Can you please submit this change as a pull request to the `devnet` branch instead of `master`?

We don't allow commits directly into `master` like this.

Cheers,
Scott

**Comment by happysmash27** [comment]
Oh, lol, I was literally just writing you an email about this! Sure thing!

**Comment by happysmash27** [comment]
Done.

**Comment by scottdonaldau** [comment]
Thanks @happysmash27  - It looks like there's a conflict now as devnet has changed since you wrote this change. Can you rebase from devnet and add your change again?

Cheers,
Scott

**Comment by scottdonaldau** [comment]
Nevermind @happysmash27  I've resolved the conflict for you 👍

**Comment by happysmash27** [comment]
Oh, thanks \(\^o\^\)丿

**Pull request merged**
